services:
  backend:
    build: ./backend
    restart: always

  frontend:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./nginx/prod.conf:/etc/nginx/conf.d/default.conf
    restart: always
    depends_on:
      - backend

  tunnel:
    container_name: cloudflared
    image: cloudflare/cloudflared:latest
    restart: always
    command: tunnel --no-autoupdate run --token eyJhIjoiNWNhZWU4OTMxNmZhZTI3NmE1MjgwMjBhODgxODkyNjIiLCJ0IjoiNjRhZGIyNzItZjNmNC00OGJiLWIyOWMtZmJjZjNiMmJkZDA4IiwicyI6IlltSTNOekEwWkRndFpETTFOUzAwTkRBM0xXSmtOMkV0WW1RMk1tWXdZelEzTTJRMyJ9
    depends_on:
      - frontend